# automatically generated from constants.pl.PL for perl 5.010000 built for MSWin32-x86-multi-thread
package AnyEvent;
sub CYGWIN(){0}
sub WIN32(){1}
sub F_SETFD(){2}
sub F_SETFL(){4}
sub O_NONBLOCK(){2048}
sub FD_CLOEXEC(){1}
package AnyEvent::Base;
sub WNOHANG(){1}
package AnyEvent::Util;
sub WSAEINVAL(){10022}
sub WSAEWOULDBLOCK(){10035}
sub WSAEINPROGRESS(){10036}
sub _AF_INET6(){23}
package AnyEvent::Socket;
sub TCP_CONGESTION(){undef}
sub TCP_CONNECTIONTIMEOUT(){undef}
sub TCP_CORK(){undef}
sub TCP_DEFER_ACCEPT(){undef}
sub TCP_INFO(){undef}
sub TCP_INIT_CWND(){undef}
sub TCP_KEEPALIVE(){undef}
sub TCP_KEEPCNT(){undef}
sub TCP_KEEPIDLE(){undef}
sub TCP_KEEPINIT(){undef}
sub TCP_KEEPINTVL(){undef}
sub TCP_LINGER2(){undef}
sub TCP_MAXSEG(){undef}
sub TCP_MD5SIG(){undef}
sub TCP_NOOPT(){undef}
sub TCP_NOPUSH(){undef}
sub TCP_QUICKACK(){undef}
sub TCP_SACK_ENABLE(){undef}
sub TCP_SYNCNT(){undef}
sub TCP_WINDOW_CLAMP(){undef}
1;
